M48
; DRILL file {KiCad 7.0.5-0} date 2025 June 01, Sunday 12:18:21
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-06-01T12:18:21-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5-0
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0315
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0354
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0433
%
G90
G05
T1
X4.35Y-4.1
X4.65Y-4.1
X4.9Y-4.1
X5.2Y-4.1
T2
X4.4Y-4.9
X4.5Y-4.9
X7.1Y-4.9
X7.2Y-4.9
T3
X3.7Y-3.9228
X3.7Y-4.1
X3.9559Y-3.9228
X3.9559Y-4.1
T0
M30
